# Generated by Django 5.1 on 2025-06-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporacion',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the corporation is published in the API'),
        ),
        migrations.AddField(
            model_name='documento',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the document is published in the API'),
        ),
        migrations.AddField(
            model_name='historicalcorporacion',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the corporation is published in the API'),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the document is published in the API'),
        ),
        migrations.AddField(
            model_name='historicallugar',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the place is published in the API'),
        ),
        migrations.AddField(
            model_name='historicalpersona',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the person is published in the API'),
        ),
        migrations.AddField(
            model_name='historicalpersonaesclavizada',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the person is published in the API'),
        ),
        migrations.AddField(
            model_name='historicalpersonanoesclavizada',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the person is published in the API'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the place is published in the API'),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the person is published in the API'),
        ),
    ]
