# Generated by Django 5.1 on 2026-03-01 23:39

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0004_add_search_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
        migrations.RenameIndex(
            model_name='corporacion',
            new_name='corporacion_search_vector_idx',
            old_name='dbgestor_co_search__idx',
        ),
        migrations.RenameIndex(
            model_name='corporacion',
            new_name='corporacion_nombre_trgm_idx',
            old_name='dbgestor_co_nombre__idx',
        ),
        migrations.RenameIndex(
            model_name='corporacion',
            new_name='corporacion_alt_trgm_idx',
            old_name='dbgestor_co_nombres_idx',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='documento_search_vector_idx',
            old_name='dbgestor_do_search__idx',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='documento_titulo_trgm_idx',
            old_name='dbgestor_do_titulo__idx',
        ),
        migrations.RenameIndex(
            model_name='documento',
            new_name='documento_desc_trgm_idx',
            old_name='dbgestor_do_descrip_idx',
        ),
        migrations.RenameIndex(
            model_name='lugar',
            new_name='lugar_search_vector_idx',
            old_name='dbgestor_lu_search__idx',
        ),
        migrations.RenameIndex(
            model_name='lugar',
            new_name='lugar_nombre_trgm_idx',
            old_name='dbgestor_lu_nombre__idx',
        ),
        migrations.RenameIndex(
            model_name='persona',
            new_name='persona_search_vector_idx',
            old_name='dbgestor_pe_search__idx',
        ),
        migrations.RenameIndex(
            model_name='persona',
            new_name='persona_nombres_trgm_idx',
            old_name='dbgestor_pe_nombres__idx',
        ),
        migrations.RenameIndex(
            model_name='persona',
            new_name='persona_apellidos_trgm_idx',
            old_name='dbgestor_pe_apellid_idx',
        ),
        migrations.RenameIndex(
            model_name='persona',
            new_name='persona_nombre_norm_trgm_idx',
            old_name='dbgestor_pe_nombre__idx',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='evento_forma_de_pago',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='evento_total',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='evento_valor_sp',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='evento_forma_de_pago',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='evento_total',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='evento_valor_sp',
        ),
        migrations.AddField(
            model_name='historicalcorporacion',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallugar',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersona',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonaesclavizada',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonanoesclavizada',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
