# Generated by Django 5.1 on 2026-03-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0005_alter_corporacion_options_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='evento_forma_de_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='evento_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='evento_valor_sp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='evento_forma_de_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='evento_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='evento_valor_sp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
