# Generated by Django 5.1 on 2026-04-17 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0006_restore_evento_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonarelaciones',
            name='persona_sujeto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dbgestor.persona'),
        ),
        migrations.AddField(
            model_name='personarelaciones',
            name='persona_sujeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaciones_como_sujeto', to='dbgestor.persona'),
        ),
        migrations.AlterField(
            model_name='historicalpersonarelaciones',
            name='naturaleza_relacion',
            field=models.CharField(choices=[('fam', 'Familiar'), ('aso', 'Asociativa'), ('tmp', 'Temporal'), ('sub', 'Subordinación')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personarelaciones',
            name='naturaleza_relacion',
            field=models.CharField(choices=[('fam', 'Familiar'), ('aso', 'Asociativa'), ('tmp', 'Temporal'), ('sub', 'Subordinación')], max_length=50),
        ),
    ]
