# Generated by Django 5.1 on 2026-05-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0007_add_subordinacion_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallugar',
            name='tipo',
            field=models.CharField(choices=[('ciudad', 'Ciudad'), ('pueblo', 'Pueblo'), ('estado', 'Estado'), ('gobernacion', 'Gobernación'), ('pais', 'País'), ('provincia', 'Provincia'), ('villa', 'Villa'), ('real', 'Real de Minas'), ('parroquia', 'Parroquia'), ('fuerte', 'Fuerte'), ('puerto', 'Puerto'), ('isla', 'Isla'), ('region', 'Región'), ('diocesis', 'Diócesis'), ('hacienda', 'Hacienda')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(choices=[('ciudad', 'Ciudad'), ('pueblo', 'Pueblo'), ('estado', 'Estado'), ('gobernacion', 'Gobernación'), ('pais', 'País'), ('provincia', 'Provincia'), ('villa', 'Villa'), ('real', 'Real de Minas'), ('parroquia', 'Parroquia'), ('fuerte', 'Fuerte'), ('puerto', 'Puerto'), ('isla', 'Isla'), ('region', 'Región'), ('diocesis', 'Diócesis'), ('hacienda', 'Hacienda')], max_length=50),
        ),
    ]
