# Generated by Django 5.1 on 2026-05-16 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0011_vocab_lowercase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('pe', 'Persona Esclavizada'), ('pn', 'Persona No Esclavizada'), ('doc', 'Documento'), ('lug', 'Lugar'), ('cor', 'Corporación')], max_length=3)),
                ('canonical_id', models.PositiveIntegerField(help_text='PK of the record to keep')),
                ('duplicate_id', models.PositiveIntegerField(help_text='PK of the record to discard')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_merge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia de merge',
                'verbose_name_plural': 'Sugerencias de merge',
                'ordering': ['-created_at'],
            },
        ),
    ]
