# Generated by Django 5.1 on 2026-07-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0012_sugerenciamerge'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeccionNivel',
            fields=[
                ('nivel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeccionPalabraClave',
            fields=[
                ('palabra_clave_id', models.AutoField(primary_key=True, serialize=False)),
                ('palabra_clave', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
