# Generated by Django 5.1 on 2026-07-20 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0013_leccion_vocab_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('leccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Sanitized HTML content, rendered as-is on the public detail page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporaciones', models.ManyToManyField(blank=True, related_name='lecciones', to='dbgestor.corporacion')),
                ('documentos', models.ManyToManyField(blank=True, related_name='lecciones', to='dbgestor.documento')),
                ('keywords', models.ManyToManyField(blank=True, related_name='lecciones', to='dbgestor.leccionpalabraclave')),
                ('levels', models.ManyToManyField(blank=True, related_name='lecciones', to='dbgestor.leccionnivel')),
                ('personas', models.ManyToManyField(blank=True, related_name='lecciones', to='dbgestor.persona')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LeccionImagen',
            fields=[
                ('leccion_imagen_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='lecciones/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='dbgestor.leccion')),
            ],
        ),
        migrations.AddIndex(
            model_name='leccion',
            index=models.Index(fields=['title'], name='leccion_title_idx'),
        ),
        migrations.AddIndex(
            model_name='leccion',
            index=models.Index(fields=['-created_at'], name='leccion_created_idx'),
        ),
    ]
