# Generated by Django 5.1 on 2026-08-30 06:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0014_leccion_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leccion',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates if the lesson is published in the API'),
        ),
        migrations.CreateModel(
            name='HistoricalLeccion',
            fields=[
                ('leccion_id', models.IntegerField(blank=True, db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Sanitized HTML content, rendered as-is on the public detail page.')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates if the lesson is published in the API')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Lección',
                'verbose_name_plural': 'historical Lecciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeccionAcceso',
            fields=[
                ('leccion_acceso_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Propietario/a'), ('collaborator', 'Colaborador/a')], default='collaborator', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='dbgestor.leccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones_accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a lección',
                'verbose_name_plural': 'Accesos a lección',
                'ordering': ['leccion', 'role', 'user'],
                'unique_together': {('leccion', 'user')},
            },
        ),
    ]
