# Generated by Django 5.1 on 2026-08-30 19:48

import dbgestor.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbgestor', '0016_publish_existing_lecciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeccionAdjunto',
            fields=[
                ('leccion_adjunto_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='lecciones/adjuntos/%Y/%m/', validators=[dbgestor.models.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='dbgestor.leccion')),
            ],
        ),
    ]
